services:
  - type: web
    name: signalsar
    runtime: python
    rootDir: signalsar
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
